x-environment: &db-env
  DB_HOST: postgres_db
  DB_PORT: 5432
  DB_NAME: dankmemes_db
  DB_PASSWORD: postgres

services:
  postgres_db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      <<: *db-env
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_db:
  app:
