x-postgres-environment: &postgres-env
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_DB: fst_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  postgres_db:
    container_name: fst_postgres_db
    image: postgres:14
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      <<: *postgres-env


volumes:
  postgres_db:
