[tool.pytest.ini_options]
pythonpath = [
    ".", ".",
]
asyncio_mode = "auto"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | alembic
  | venv
)/
'''

[tool.flake8]
ignore = ["E203", "E266", "E501", "W503", "F403", "F401", "E231"]
max-line-length = 88
max-complexity = 18
select = ["B", "C", "E", "F", "W", "T4", "B9"]
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__",
]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.13"
strict = "False"

mypy_path = "./app"

ignore_missing_imports = "True"

disallow_untyped_defs = "True"
disallow_untyped_calls = "True"
disallow_incomplete_defs = "True"
check_untyped_defs = "True"

warn_return_any = "False"
warn_unused_configs = "True"
warn_unused_ignores = "True"
warn_redundant_casts = "True"

plugins = "pydantic.mypy"
